// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Menu → Menu Links*
 */
export interface MenuDocumentDataMenuLinksItem {
  /**
   * Label field in *Menu → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Menu → Menu Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Title field in *Menu*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * background field in *Menu*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;

  /**
   * Menu Links field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_links: prismic.GroupField<Simplify<MenuDocumentDataMenuLinksItem>>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MenuDocumentData>, "menu", Lang>;

/**
 * Primary content in *Page → Slice Zone → Banner with caption → Primary*
 */
export interface PageDocumentDataBodyBannerWithCaptionSlicePrimary {
  /**
   * Image Banner field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].banner_with_caption.primary.image_banner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_banner: prismic.ImageField<never>;

  /**
   * Image Position field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Image Position
   * - **API ID Path**: page.body[].banner_with_caption.primary.image_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_position: prismic.SelectField<"left" | "right">;

  /**
   * Title Of banner field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: My title of banner
   * - **API ID Path**: page.body[].banner_with_caption.primary.title_of_banner
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_of_banner: prismic.RichTextField;

  /**
   * Description field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: My description
   * - **API ID Path**: page.body[].banner_with_caption.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTa Title field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].banner_with_caption.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * Button Link field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select the link
   * - **API ID Path**: page.body[].banner_with_caption.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * background field in *Page → Slice Zone → Banner with caption → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].banner_with_caption.primary.background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataBodyBannerWithCaptionSlice = prismic.Slice<
  "banner_with_caption",
  Simplify<PageDocumentDataBodyBannerWithCaptionSlicePrimary>,
  never
>;

/**
 * Item content in *Page → Slice Zone → Hero → Items*
 */
export interface PageDocumentDataBodyHeroSliceItem {
  /**
   * Image field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Background field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;

  /**
   * CTA Title field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA Link field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.ContentRelationshipField;

  /**
   * CTA color field in *Page → Slice Zone → Hero → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].hero.items.cta_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cta_color: prismic.ColorField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataBodyHeroSlice = prismic.Slice<
  "hero",
  Record<string, never>,
  Simplify<PageDocumentDataBodyHeroSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Icon Inline List → Primary*
 */
export interface PageDocumentDataBodyIconInlineListSlicePrimary {
  /**
   * Title field in *Page → Slice Zone → Icon Inline List → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].icon_inline_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * background field in *Page → Slice Zone → Icon Inline List → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].icon_inline_list.primary.background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;
}

/**
 * Item content in *Page → Slice Zone → Icon Inline List → Items*
 */
export interface PageDocumentDataBodyIconInlineListSliceItem {
  /**
   * icon image field in *Page → Slice Zone → Icon Inline List → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].icon_inline_list.items.icon_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon_image: prismic.ImageField<never>;

  /**
   * Icon Title field in *Page → Slice Zone → Icon Inline List → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].icon_inline_list.items.icon_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  icon_title: prismic.TitleField;

  /**
   * Icon Description field in *Page → Slice Zone → Icon Inline List → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].icon_inline_list.items.icon_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  icon_description: prismic.RichTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataBodyIconInlineListSlice = prismic.Slice<
  "icon_inline_list",
  Simplify<PageDocumentDataBodyIconInlineListSlicePrimary>,
  Simplify<PageDocumentDataBodyIconInlineListSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Rich Text → Primary*
 */
export interface PageDocumentDataBodyTextSlicePrimary {
  /**
   * Title field in *Page → Slice Zone → Rich Text → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * text field in *Page → Slice Zone → Rich Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Your content here
   * - **API ID Path**: page.body[].text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * background field in *Page → Slice Zone → Rich Text → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].text.primary.background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Simplify<PageDocumentDataBodyTextSlicePrimary>,
  never
>;

/**
 * Primary content in *Page → Slice Zone → Blog Post → Primary*
 */
export interface PageDocumentDataBodyBlogPostSlicePrimary {
  /**
   * Article Title field in *Page → Slice Zone → Blog Post → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].blog_post.primary.article_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_title: prismic.TitleField;

  /**
   * Article Content field in *Page → Slice Zone → Blog Post → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].blog_post.primary.article_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_content: prismic.RichTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataBodyBlogPostSlice = prismic.Slice<
  "blog_post",
  Simplify<PageDocumentDataBodyBlogPostSlicePrimary>,
  never
>;

/**
 * Primary content in *Page → Slice Zone → Grid → Primary*
 */
export interface PageDocumentDataBodyGridSlicePrimary {
  /**
   * heading field in *Page → Slice Zone → Grid → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Item content in *Page → Slice Zone → Grid → Items*
 */
export interface PageDocumentDataBodyGridSliceItem {
  /**
   * image field in *Page → Slice Zone → Grid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].grid.items.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Page → Slice Zone → Grid → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].grid.items.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *Page → Slice Zone → Grid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].grid.items.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cta_title field in *Page → Slice Zone → Grid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].grid.items.cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * url field in *Page → Slice Zone → Grid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[].grid.items.cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_url: prismic.LinkField;

  /**
   * external field in *Page → Slice Zone → Grid → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.body[].grid.items.cta_external
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_external: prismic.BooleanField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataBodyGridSlice = prismic.Slice<
  "grid",
  Simplify<PageDocumentDataBodyGridSlicePrimary>,
  Simplify<PageDocumentDataBodyGridSliceItem>
>;

type PageDocumentDataBodySlice =
  | FeaturesSlice
  | PageDocumentDataBodyBannerWithCaptionSlice
  | PageDocumentDataBodyHeroSlice
  | PageDocumentDataBodyIconInlineListSlice
  | PageDocumentDataBodyTextSlice
  | PageDocumentDataBodyBlogPostSlice
  | PageDocumentDataBodyGridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<PageDocumentDataBodySlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = MenuDocument | PageDocument;

/**
 * Item in *Features → Default → Primary → Feature Grid*
 */
export interface FeaturesSliceDefaultPrimaryFeatureGridItem {
  /**
   * Icon field in *Features → Default → Primary → Feature Grid*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.feature_grid[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Features → Default → Primary → Feature Grid*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Feature Title
   * - **API ID Path**: features.default.primary.feature_grid[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Features → Default → Primary → Feature Grid*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature Description
   * - **API ID Path**: features.default.primary.feature_grid[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Default → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Title field in *Features → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Title
   * - **API ID Path**: features.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Feature Grid field in *Features → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.feature_grid[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feature_grid: prismic.GroupField<
    Simplify<FeaturesSliceDefaultPrimaryFeatureGridItem>
  >;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataMenuLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataBodyBannerWithCaptionSlicePrimary,
      PageDocumentDataBodyHeroSliceItem,
      PageDocumentDataBodyIconInlineListSlicePrimary,
      PageDocumentDataBodyIconInlineListSliceItem,
      PageDocumentDataBodyTextSlicePrimary,
      PageDocumentDataBodyBlogPostSlicePrimary,
      PageDocumentDataBodyGridSlicePrimary,
      PageDocumentDataBodyGridSliceItem,
      PageDocumentDataBodySlice,
      AllDocumentTypes,
      FeaturesSlice,
      FeaturesSliceDefaultPrimaryFeatureGridItem,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
    };
  }
}
